# TODO: make 'gp' - go previous to pwd (where open)
[manager]
prepend_keymap = [
    {on = [ "g", "r" ], run = '''shell 'ya emit cd "$(git rev-parse --show-toplevel)"'''', desc = "Return git root"},
    {on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here"},

    # Smart-paste
    {on = "p", run = 'plugin smart-paste', desc = "Paste into the hovered directory or CWD"},
    # Toggle pane
    {on = "T", run = "plugin toggle-pane max-preview", desc = "Maximize or restore preview"},
    # Mount
    {on = "M", run = "plugin mount", desc = "Mount plugin"},
    
    # Chmod
    {on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files"},
    # First non-dir file plug
    {on = ["g", "j"], run = "plugin first-non-directory", desc = "Jump to the first file"},
    
    # Relative motions
    {on = "1", run = "plugin relative-motions 1", desc = "Move in relative steps"},
    {on = "2", run = "plugin relative-motions 2", desc = "Move in relative steps"},
    {on = "3", run = "plugin relative-motions 3", desc = "Move in relative steps"},
    {on = "4", run = "plugin relative-motions 4", desc = "Move in relative steps"},
    {on = "5", run = "plugin relative-motions 5", desc = "Move in relative steps"},
    {on = "6", run = "plugin relative-motions 6", desc = "Move in relative steps"},
    {on = "7", run = "plugin relative-motions 7", desc = "Move in relative steps"},
    {on = "8", run = "plugin relative-motions 8", desc = "Move in relative steps"},
    {on = "9", run = "plugin relative-motions 9", desc = "Move in relative steps"},
    # Switch tab
    {on = "<a-1>", run = "tab_switch 0", desc = "switch tab"},
    {on = "<a-2>", run = "tab_switch 1", desc = "switch tab"},
    {on = "<a-3>", run = "tab_switch 2", desc = "switch tab"},
    {on = "<a-4>", run = "tab_switch 3", desc = "switch tab"},
    {on = "<a-5>", run = "tab_switch 4", desc = "switch tab"},
    {on = "<a-6>", run = "tab_switch 5", desc = "switch tab"},
    {on = "<a-7>", run = "tab_switch 6", desc = "switch tab"},
    {on = "<a-8>", run = "tab_switch 7", desc = "switch tab"},
    {on = "<a-9>", run = "tab_switch 8", desc = "switch tab"},
]
