[manager]
prepend_keymap = [
    {on = [ "g", "r" ], run = '''shell 'ya emit cd "$(git rev-parse --show-toplevel)"'''', desc = "Return git root"},
    {on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here"},

    # Smart-paste
    {on = "p", run = 'plugin smart-paste', desc = "Paste into the hovered directory or CWD"},
    # Toggle pane
    {on = "T", run = "plugin toggle-pane max-preview", desc = "Maximize or restore preview"},
    # Mount
    {on = "M", run = "plugin mount", desc = "Mount plugin"},
    
    # Chmod
    {on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files"},
    # First non-dir file plug
    {on = ["g", "j"], run = "plugin first-non-directory", desc = "Jump to the first file"},
]
