# TODO: make 'gp' - go previous to pwd (where open)
[manager]
prepend_keymap = [
    {on = [ "g", "r" ], run = '''shell 'ya emit cd "$(git rev-parse --show-toplevel)"'''', desc = "Return git root"},
    {on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here"},
    # Chmod plug
    {on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files"},

    # Max preview
    {on = "T", run = "plugin max-preview", desc = "Maximize or restore preview"},

    # Bypass plug
    {on = "<a-l>", run = "plugin bypass", desc = "Recursively enter child directory, skipping children with only a single subdirectory"},
    {on = "<a-h>", run = "plugin bypass --args=reverse", desc = "Recursively enter child directory, skipping children with only a single subdirectory"},
    # First non-dir file plug
    {on = ["g", "j"], run = "plugin first-non-directory", desc = "Jump to the first file"},
    #Custom shell plugin
    {on = ":", run = 'plugin custom-shell --args="auto --interactive"', desc = "Jump to the first file"},
    
    # Bookmarks plugin
    # TODO: add relative path marks (starts with ~/)
    {on = "m", run = "plugin bookmarks --args=save", desc = "Save current position as a bookmark"},
    {on = "'", run = "plugin bookmarks --args=jump", desc = "Jump to a bookmark"},
    {on = ["b", "d"], run = "plugin bookmarks --args=delete", desc = "Delete a bookmark"},
    {on = ["b", "D"], run = "plugin bookmarks --args=delete_all", desc = "Delete all bookmarks"},

    # Relative motions plug
    {on = "1", run = "plugin relative-motions --args=1", desc = "Move in relative steps"},
    {on = "2", run = "plugin relative-motions --args=2", desc = "Move in relative steps"},
    {on = "3", run = "plugin relative-motions --args=3", desc = "Move in relative steps"},
    {on = "4", run = "plugin relative-motions --args=4", desc = "Move in relative steps"},
    {on = "5", run = "plugin relative-motions --args=5", desc = "Move in relative steps"},
    {on = "6", run = "plugin relative-motions --args=6", desc = "Move in relative steps"},
    {on = "7", run = "plugin relative-motions --args=7", desc = "Move in relative steps"},
    {on = "8", run = "plugin relative-motions --args=8", desc = "Move in relative steps"},
    {on = "9", run = "plugin relative-motions --args=9", desc = "Move in relative steps"},
    # Switch tab
    {on = "<a-1>", run = "tab_switch 0", desc = "switch tab"},
    {on = "<a-2>", run = "tab_switch 1", desc = "switch tab"},
    {on = "<a-3>", run = "tab_switch 2", desc = "switch tab"},
    {on = "<a-4>", run = "tab_switch 3", desc = "switch tab"},
    {on = "<a-5>", run = "tab_switch 4", desc = "switch tab"},
    {on = "<a-6>", run = "tab_switch 5", desc = "switch tab"},
    {on = "<a-7>", run = "tab_switch 6", desc = "switch tab"},
    {on = "<a-8>", run = "tab_switch 7", desc = "switch tab"},
    {on = "<a-9>", run = "tab_switch 8", desc = "switch tab"},
]
