[manager]
ratio = [2,5,7]
sort_sensitive = false
sort_dir_first = true
show_symlink = true
linemode = "size"

[preview]
wrap = "no"
# Different image settings 
# https://yazi-rs.github.io/docs/configuration/yazi#preview.image_quality
image_fiter = "nearest" 
image_quality = 60

[opener]
play = [
    { run = 'mpv "$@"', desc = "mpv player", orphan = true }
]
img_viewer = [
    { run = 'shotwell "$@"', desc = "shotwell img viewer", orphan = true }
]
edit = [
	{ run = '$EDITOR "$@"', desc = "nvim editor", block = true },
]
torrent = [
    { run = 'transmission-qt "$@"', desc = "transmiision torrent", orphan = true}
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]

rules = [
    { name = "folder/*", use = "edit" },
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = "img_viewer" },
    { mime = "video/*", use = "play"},
]

append_previewers = [
    { name = "*", run = "hexyl" },
]
